apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
type: Opaque
stringData:
  age.agekey: |
    # created: 2026-03-27T23:38:03-04:00
    # public key: age1s20z4xf3c7l6ycmmta4peu062dk5k7g3g6ezzdz3kzf7kepq09jqyetlrv
    AGE-SECRET-KEY-10RAZ0HZDDZN85A5N3JWTE4HE6KNCQWZG5NN3LN38KKFZK37UA2KSUHKSEQ
