apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - local-path-storage.yaml
  - namespace.yaml
  - gitrepository.yaml
  - helmrelease.yaml
  - helmrelease-frontend.yaml
  - helmrelease-worker.yaml
  - helmrelease-postgres.yaml
  - helmrelease-redis.yaml
  - secrets/mission-control-secrets.yaml
