apiVersion: v1
kind: Secret
metadata:
    name: mission-control-secrets
    namespace: mission-control
type: Opaque
stringData:
    LOCAL_AUTH_TOKEN: ENC[AES256_GCM,data:pOhWZX3w6pFd2d7Ao4gSVhnkniZb3V4t2mstoVpDxB4bAJaHBM1TYIuZgbHMI2jPVzjXS5CrPirIMYexYlVXwQ==,iv:VvFsBit7JgylME+gSf3SihO4ZsxwJmN839+ZThEmd3w=,tag:olphlWCBErbkzto2+law+Q==,type:str]
sops:
    age:
        - recipient: age1s20z4xf3c7l6ycmmta4peu062dk5k7g3g6ezzdz3kzf7kepq09jqyetlrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaHNaNm9RUmtVMUcyWmdw
            QjBHandmNHpSOWZDbWwrMnRDaHpreWFYZVdrCk1vUDdWNHM4dDJhbHBlTXFqRXFL
            N1FnMjdDdW5NazExdDRNTkZBZnUyYk0KLS0tIG1kSG5pQjJHa3dOUm5rclZHTkt3
            YWI3M2xQM0NEbkJ6SnErSVk3aTQvY1EKsVsjOVU0H+D0d53Y4XTnEtqAM6hwaDkw
            bFsLrZ9R/9UDT4DXoxyIBIXT6VYPjKNDlfLjhG9ApgODkmIug+8nJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T02:33:16Z"
    mac: ENC[AES256_GCM,data:abEPLl5D00hGRbNEehi5Dy7C8hdcvgdK6hORJsLdeYfwBzPG7gjqke7J7oTo/xaQDKXQiilEBiX0mtdBCuiqY9naisJ/vfTPIj6KJ61JCV5/CV0u1pWFpgH2kkImU6wqwHznc2UVOBSZLH9+x6TiSmlNp2oCnxA4DSvnopNeKs4=,iv:J2SjOPQZr6wc0EjcBP+7UNGQLjYv8icNXoWZ1pGLH5w=,tag:dQmlJel27Ty5IAgvABmIOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
