apiVersion: v1
kind: Secret
metadata:
    name: mission-control-secrets
    namespace: mission-control
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:N430OKktgUFRQxsqZYWV2tEsdCGSZZ88Ayl+MeQ3y17ewtlKq0ruj/38/hKueXijuozZbmHM1Jo6GX9B2BPB89MIVZcQ,iv:q9NrxQp0fNhNQvN7R82ctGEacOwVearK5lyV0SVerLA=,tag:tbKSKyHqq0VmqN24rHOqyw==,type:str]
    LOCAL_AUTH_TOKEN: ENC[AES256_GCM,data:bveJUXnoZ/BgT66qEFgt8JfBHl6Ycc9I69nC4TLOa708skPoc1slQVS09g==,iv:i/PPPCqF4+XDVu3hYbQdpsD9LRtMoggkNWlCSqopNAk=,tag:Umas6QkOHBCSoptcMdLWEg==,type:str]
sops:
    age:
        - recipient: age1s20z4xf3c7l6ycmmta4peu062dk5k7g3g6ezzdz3kzf7kepq09jqyetlrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSUZyZmtsVnkybVRMYjFm
            ZGhQeVFpZ0haWXllMEFUeW1TSzZoNnNPb0NVClB4cFJmQWN6dloxOWo4Y0pGWmRp
            NVV4K3NLN3NEcVI2NnhtZkdlN1FNL3cKLS0tIEVzNExMUXJHdFRvbDc1N3haa3Ju
            blNyM1lVMEVmMFlTaGsvWUZYT3VESGcKDAieN3UxNdAlG5eAX2kkLhf5oUQJ1eqU
            I+nctEBA/mB3whTFUGpLAGBPBeOqMJIf8plMrOprUh1F8osQEu6JjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T02:05:45Z"
    mac: ENC[AES256_GCM,data:5uQwSez7r0IxTrpEPJn+QG4EjGWFwXVxghHvr+fUoQMcsxY6q/4Px3ROlJdV+GXWVB09ewS5bEW6dTTHAlfwD9Xmxw+jV/V7rY+KFO/+7AJ/9ZHVUhMoJnyPrMIAwO9VvnBH8xtrXgL/ROXSQA06TzjeiawHv1FZDxRN8EjDVBY=,iv:206PyEhFTY1aJ3jmeL9IjpaJdj8lJaFY5b2K4YixSJc=,tag:isj5HdUgqfFmFgSVaZpMDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
