apiVersion: v1
kind: Secret
metadata:
    name: mission-control-secrets
    namespace: mission-control
type: Opaque
stringData:
    LOCAL_AUTH_TOKEN: ENC[AES256_GCM,data:jk0UcMOGBzEwwQ1rnCixopZGdbL2H/YTlG2Krf4=,iv:yTdDpU4EaR4EGFooQ2mf8tVCt9XkqWwvgcp0DMmAJOw=,tag:PBpy5hPSIGpMNxBp/G+oyQ==,type:str]
sops:
    age:
        - recipient: age1s20z4xf3c7l6ycmmta4peu062dk5k7g3g6ezzdz3kzf7kepq09jqyetlrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOajBaZ3JCZm96eW02b3pq
            SVcrSnpZWWFrcEtXejJNNzRxQmJTNzh0ZWtzCmp5Y1QvbE5acXpobEh6ZjdXZkJs
            SGtUOXN6QkVldDIvdm93cjFQUzlnencKLS0tIGI3bmpodHNTZ2Y1MFYzRGhadTU0
            RGozWkVNNEEzNlNYVCtEaU54bzJ6czgKQTFZO38n0Jd9XqnMiseGypo98tnYcR4M
            s/YwkJLQziWnpxYNoOwnQMJCJ2vrp9Jy2ziBj5Xq1CmlfBeV6lG99g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T03:38:16Z"
    mac: ENC[AES256_GCM,data:op9HO91UeLByYb1MLhzWCOXfiSEkmrLdYTo5ScDbFULuPj7vHt46bYhsManrVVc599OT+TEXjZZG1DhHJQ21pnnkzvrGMZo1/pWJzBllq9xa/kNetlunDO+gaeLlSA5oXniJ/CewZ5Vd6rA2IwTax4tUjiYEiFJz16CyC4DSCvo=,iv:y5RfPRuaWwl+UarSeDWRe+Td4ZnjCazowCHvIn6UdT4=,tag:/o0MuVIZgo8GrBSZRVSIjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
